---

"COURSE": "CAU_DRALG_2023"
"ASSIGNMENT": "ASSIGNMENT_05"

"ID": "20210162"
"FILES":
    - "C:/Users/82106/cau-dralg-2023/assignment_05/singlylinkedlist.py" 
"PROBLEMS": 
    - "PROBLEM_01"
    - "PROBLEM_02"
    - "PROBLEM_03"
    - "PROBLEM_04"
    - "PROBLEM_05"
    - "PROBLEM_06"
    - "PROBLEM_07"
    - "PROBLEM_08"
    - "PROBLEM_09"
    - "PROBLEM_10"
    - "PROBLEM_11"
        
