---

"COURSE": "CAU_DRALG_2023"
"ASSIGNMENT": "ASSIGNMENT_03"

"ID": "20001234"
"FILES":
    - "path-to-your-course/cau_oop_2022/assignment_03/mathlib.cpp"
    - "path-to-your-course/cau_oop_2022/assignment_03/mathlib.h"
"PROBLEMS": 
    - "PROBLEM_01A"
    - "PROBLEM_01B"
    - "PROBLEM_01C"
    - "PROBLEM_01D"
    - "PROBLEM_01E"

    - "PROBLEM_02A"
    - "PROBLEM_02B"
    - "PROBLEM_02C"
    - "PROBLEM_02D"
    - "PROBLEM_02E"
    
