---

"COURSE": "CAU_DRALG_2023"
"ASSIGNMENT": "ASSIGNMENT_03"

"ID": "20210162"
"FILES":
    - "/D:/repos/bdc-client/cau-dralg-2023/assignment_03/array_utils.py" 
"PROBLEMS": 
    - "PROBLEM_01A"
    - "PROBLEM_01B"
    - "PROBLEM_01C"
    - "PROBLEM_01D"
    - "PROBLEM_01E"

    - "PROBLEM_02A"
    - "PROBLEM_02B"
    - "PROBLEM_02C"
    - "PROBLEM_02D"
    - "PROBLEM_02E"
    
