---

"COURSE": "CAU_DRALG_2023"
"ASSIGNMENT": "ASSIGNMENT_04"

"ID": "20210162"
"FILES":
    - "C:/Users/82106/cau-dralg-2023/assignment_04/history.py" 
"PROBLEMS": 
    - "PROBLEM_01"
    - "PROBLEM_02"
    - "PROBLEM_03"
    - "PROBLEM_04"
    - "PROBLEM_05"
    - "PROBLEM_06"
        
